### ISSUE TITLE
Error during installation on Ubuntu

### ISSUE THREAD

**Issue by rebhand** [TUW-VieVS/VieSchedpp#7]
**Describe the bug**
The manual installation failed when I ran the make command after the second "cmake -DCMAKE_BUILD_TYPE=Release .." (after "git clone https://github.com/TUW-VieVS/VieSchedpp.git"). I tried with both "-DCMAKE" and "-DCAMKE" in the step before (mentioned in issue #6). This seems to be a compilation error, independent of the libraries installed.

**Version number**
759e79c1b2dcd3c8070e5af344f454f20d32dc98, most recent download

**Screenshots / Output**
Full output on terminal of entire installation process: 
[terminal.txt](https://github.com/TUW-VieVS/VieSchedpp/files/7310649/terminal.txt)
Screenshot for the error message:
![image](https://user-images.githubusercontent.com/92156240/136542879-de884007-1843-4269-8e9c-8e058bb2af72.png)

**Desktop (please complete the following information):**
I am working with Xubuntu 21.04 and gcc 10.3.0.

**Additional context**
Comment on terminal output in txt file: Line 299, "*** Now type 'make test'  to install the library and run tests ***". I did this the first time when I went through the installation guide and everything was fine. This is my second attempt to install manually.

**Comment by rebhand** [comment]
I have been advised to separate the problems mentioned here into two separate issues. Thus: Removed part of the comment and created issue #8.
